spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meddoc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user12345
  jpa:
    show-sql: false

app:
  address-file-path: 'E:\Projects\MyJavaProject\KLADR_to_FIAS_migration\description\dbf\'
  address-file-name: 'fias_dbf_lite.zip'
