spring:
  datasource:
    url: jdbc:mysql://localhost:3306/databasename
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: pass
  jpa:
    show-sql: false

app:
  address-file-path: 'E:\Projects\dbf\'
  address-file-name: 'dbf.zip'
